import{chromium}from'@playwright/test';import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';
const base=process.env.PUNTOES_URL||'http://127.0.0.1:4180/',out=process.env.PUNTOES_QA_OUT||'docs/coordinacion-mano-2026-10-01/TRAMO-820-C2-LUZ';const maxPower=Number(process.env.PUNTOES_LIGHT_MAX||8),skipIsolated=process.env.PUNTOES_SKIP_ISOLATED==='1';await mkdir(out,{recursive:true});const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={date:new Date().toISOString(),url:base,errors:[],real:[],isolated:[],fallbacks:[]};
const state=p=>p.evaluate(()=>window.__puntoes.getState());async function ready(p,url=base){p.on('pageerror',e=>report.errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>document.body.dataset.render==='webgl',null,{timeout:60000});await p.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#scene canvas')).opacity)>.99)}
async function jump(p,m){await p.evaluate(m=>scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*m/1000,behavior:'instant'}),m);await p.waitForFunction(m=>Math.abs(window.__puntoes.getState().visualProgress-m/200)<.002,m);await p.waitForFunction(()=>Math.abs(window.__puntoes.getState().visualProgress-window.__puntoes.getState().progress)<.00001)}
const stable=x=>JSON.parse(JSON.stringify(x,(k,v)=>typeof v==='number'?Math.round(v*1e5)/1e5:v));
try{
 const p=await b.newPage({viewport:{width:1424,height:873}});await ready(p);
 for(const m of [250,500,820,1000]){await jump(p,m);for(const[name,x,y]of [['izquierda',280,436],['centro',712,436],['derecha',1190,436]]){await p.mouse.move(x,y);await p.waitForTimeout(1500);const s=await state(p),light=s.scene.cursorLight;assert.ok(light.enabled&&light.intensity<=maxPower+.00001&&light.clearance>=.14);assert.ok(light.projectionError<1e-10);assert.ok(Math.abs((light.projection[0]+1)*712-x)<.01);assert.ok(Math.abs((1-light.projection[1])*873/2-y)<.01);assert.ok(light.actorCount>=2);await p.screenshot({path:`${out}/REAL-${m}-${name}.png`});report.real.push({marker:m,pointer:name,pixel:[x,y],state:s})}}await p.close();
 if(!skipIsolated){const probe=await b.newPage({viewport:{width:1424,height:873}});await ready(probe,`${base}tests/fixtures/cursor-light-studio.html`);
 for(const m of [250,500,820,1000]){let first;for(const[name,x]of [['izquierda',-.65],['centro',0],['derecha',.65]]){await probe.evaluate(({m,x})=>window.__surfaceLightProbe.set(m,x,0),{m,x});await probe.waitForTimeout(1500);const s=await probe.evaluate(()=>window.__surfaceLightProbe.getState());assert.ok(s.cursorLight.projectionError<1e-10);if(first){assert.deepEqual(s.camera,first.camera);assert.deepEqual(s.fingerJoints,first.fingerJoints);assert.deepEqual(s.humanPosition,first.humanPosition);assert.deepEqual(s.tools,first.tools)}else first=s;await probe.screenshot({path:`${out}/AISLADA-${m}-${name}.png`});report.isolated.push({marker:m,pointer:name,state:s})}}await probe.close();}
 for(const config of [{viewport:{width:390,height:844},reducedMotion:'reduce'},{viewport:{width:390,height:844},hasTouch:true,isMobile:true}]){const ctx=await b.newContext(config),p=await ctx.newPage();await ready(p,`${base}?scroll=820`);await p.waitForTimeout(1200);let s=await state(p);assert.equal(s.scene.cursorLight.enabled,false);assert.equal(s.scene.cursorLight.intensity,0);await p.mouse.move(20,20);await p.waitForTimeout(1000);s=await state(p);assert.equal(s.scene.cursorLight.enabled,false);assert.ok(s.scene.cursorLight.projectionError<1e-10);await p.screenshot({path:`${out}/FALLBACK-${config.reducedMotion?'REDUCIDO':'TACTIL'}.png`});report.fallbacks.push({config,state:s});await ctx.close()}
 assert.deepEqual(report.errors,[]);report.passed=true;console.log('✓ Raw cursor projection, real PBR with fixed camera, reduced and touch fallbacks');
}catch(e){report.failure=e.stack;console.error(e);process.exitCode=1}finally{await writeFile(`${out}/VALIDACION-LUZ.json`,JSON.stringify(report,null,2));await Promise.race([b.close(),new Promise(resolve=>setTimeout(resolve,5000))]);process.exit(process.exitCode||0)}
