// Historical audit before the reference-driven hand choreography; superseded by experience.mjs.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.PUNTOES_URL||'http://127.0.0.1:4177/',output=path.resolve('docs/coreografia-mano');await mkdir(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.PUNTOES_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const report={date:new Date().toISOString(),url:base,rendering:'Chromium / SwiftShader: composición y funcionamiento, no rendimiento en GPU física',checks:[],captures:[],errors:[]};
const state=p=>p.evaluate(()=>window.__puntoes.getState());const record=name=>{report.checks.push(name);console.log('✓ '+name)};
function observe(p){p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/Shader Error|ERROR: 0:|INVALID_OPERATION/.test(m.text()))report.errors.push(m.text())})}
async function ready(p){observe(p);await p.goto(base);await p.waitForFunction(()=>document.body.dataset.render==='webgl',null,{timeout:45000});await p.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#scene canvas')).opacity)>.99)}
async function jump(page,p){await page.evaluate(p=>{const c=[...document.querySelectorAll('[data-scene]')],i=Math.min(4,Math.floor(p)),end=c[i+1]?.offsetTop??document.documentElement.scrollHeight-innerHeight;scrollTo({top:c[i].offsetTop+(end-c[i].offsetTop)*(p-i),behavior:'instant'})},p);await page.waitForFunction(p=>Math.abs(window.__puntoes.getState().visualProgress-p)<.004,p,{timeout:15000});await page.waitForFunction(()=>window.__puntoes.getState().scroll.moving!=='smooth')}
async function capture(p,name){await p.screenshot({path:path.join(output,name+'.png')});report.captures.push({name:name+'.png',viewport:p.viewportSize(),state:await state(p)})}
try{
 const page=await browser.newPage({viewport:{width:1424,height:873}});await ready(page);
 assert.equal((await state(page)).scene.humanVisible,false);const title=await page.locator('#hero-title').boundingBox();assert.ok(Math.abs(title.x+title.width/2-712)<2);await capture(page,'FINAL-00-inicio');record('Carga con título centrado y sin mano visible');
 assert.equal(await page.locator('#piedra,#idea,#alcance,#repeticion,#punto,#criterio,#servicios,#consultoria,#aplicacion,#metodo,#contacto').count(),0);assert.equal(await page.locator('[data-scene]').count(),5);assert.equal(await page.locator('form').count(),0);record('La página activa contiene cinco tramos visuales; el argumentario y los objetos anteriores se han retirado');
 const milestones=[['02',.68],['03',1.15],['04',1.7],['05',2.2],['06',2.65],['07',3.05],['08',3.5],['09',4],['10',4.4],['11',4.75]];
 for(const [label,p] of milestones){
  await jump(page,p);await page.mouse.move(712,436);await page.waitForTimeout(500);await capture(page,'FINAL-'+label+'-centro');const s=await state(page);assert.ok(s.scene.actors.every(a=>['human-hand','ai-hand','puntoes-orbits'].includes(a)));assert.equal(s.scene.aiVisible,p>3.15);
  const views=[];for(const [corner,x,y] of [['arriba-izquierda',80,120],['arriba-derecha',1340,120],['abajo-derecha',1340,740],['abajo-izquierda',80,740]]){await page.mouse.move(x,y);await page.waitForFunction(({x,y})=>{const p=window.__puntoes.getState().pointer;return Math.abs(p.x-(x/innerWidth*2-1))<.03&&Math.abs(p.y-(1-y/innerHeight*2))<.03},{x,y});await capture(page,'FINAL-'+label+'-'+corner);views.push((await state(page)).scene.camera);assert.ok(Math.abs((await state(page)).progress-p)<.003)}assert.ok(Math.max(...views.map(v=>v[0]))-Math.min(...views.map(v=>v[0]))>1);assert.ok(Math.max(...views.map(v=>v[1]))-Math.min(...views.map(v=>v[1]))>.7);
 }
 record('Diez avances revisados desde el centro y las cuatro esquinas: perspectiva real sin avance de la historia');
 await jump(page,1.7);assert.equal((await state(page)).scene.orbits.discs.length,9);const before=(await state(page)).scene.orbits.discs;await page.waitForTimeout(1400);const after=(await state(page)).scene.orbits.discs;assert.ok(after.some((d,i)=>Math.abs(d.z-before[i].z)>.05));await jump(page,3.1);assert.equal((await state(page)).scene.orbits.visible,false);record('Los nueve discos orbitan en profundidad y desaparecen durante la extensión');
 await jump(page,.68);const idle=[];for(let i=0;i<5;i++){await page.waitForTimeout(1000);idle.push(await state(page))}assert.ok(Math.max(...idle.map(s=>s.scene.humanPosition[2]))-Math.min(...idle.map(s=>s.scene.humanPosition[2]))>.05);assert.ok(idle.every(s=>s.progress===idle[0].progress));assert.ok(idle.at(-1).scene.fingerCurls.slice(2).every((v,i)=>Math.abs(v-idle[0].scene.fingerCurls[i+2])>.0001));record('La aparición mantiene el vaivén y los tres dedos vivos al detener el scroll');
 await page.mouse.move(712,436);await jump(page,4.75);const last=await state(page);assert.ok(last.scene.contactGap>.12&&last.scene.contactGap<.25,String(last.scene.contactGap));const [left,right]=[last.scene.screenLandmarks.foreground,last.scene.screenLandmarks.second];assert.ok(left[0]<right[0]&&right[0]-left[0]<1424*.055);assert.ok(Math.abs(left[1]-right[1])<873*.035);await capture(page,'FINAL-encuentro');record('El cierre deja una pequeña separación entre índices y mantiene su altura cercana');
 for(const p of [4.4,3.5,2.2,1.15,.68,0]){await jump(page,p);assert.equal((await state(page)).scene.aiVisible,p>3.15)}assert.equal((await state(page)).scene.humanVisible,false);assert.equal((await state(page)).editorial.beats.title.opacity,1);record('Todo el recorrido se deshace hasta el título inicial');
 await page.mouse.wheel(0,900);const wheel=await page.evaluate(async()=>{const values=[];const start=performance.now();while(performance.now()-start<2200){await new Promise(requestAnimationFrame);values.push(window.__puntoes.getState().scroll.current)}return values});assert.ok(new Set(wheel.map(v=>Math.round(v))).size>5);assert.ok(wheel.every((v,i)=>!i||v>=wheel[i-1]-.5));await page.keyboard.press('End');await page.waitForFunction(()=>window.__puntoes.getState().progress>4.99);record('Rueda suavizada y teclado permiten alcanzar el último encuadre');
 await page.getByRole('button',{name:'Clientes',exact:true}).click();assert.equal(await page.locator('dialog[open] .client-list img').count(),9);const paused=(await state(page)).progress;await page.mouse.wheel(0,-900);await page.waitForTimeout(600);assert.equal((await state(page)).progress,paused);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);record('La lista accesible de clientes abre, conserva el scroll y cierra con Escape');
 await page.reload();await page.waitForFunction(()=>document.body.dataset.render==='webgl');assert.equal((await state(page)).progress,0);assert.equal((await page.context().cookies()).length,0);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);record('Recarga desde el final: vuelve al inicio sin guardar progreso');
 await page.getByRole('link',{name:'El encuentro',exact:false}).click();await page.waitForFunction(()=>Math.abs(window.__puntoes.getState().visualProgress-4.68)<.005);assert.ok(await page.locator('.replay').isVisible());await page.locator('.replay').click();await page.waitForFunction(()=>window.__puntoes.getState().progress<.001);record('Los accesos a encuentro e inicio funcionan en ambos sentidos');await page.close();
 for(const viewport of [{width:320,height:640},{width:390,height:844},{width:768,height:1024}]){const phone=await browser.newPage({viewport});await ready(phone);assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture(phone,`MOVIL-${viewport.width}-inicio`);for(const p of [1.7,2.65,4.75]){await jump(phone,p);const s=await state(phone);assert.ok(s.scene.screenLandmarks.foreground[0]>0&&s.scene.screenLandmarks.foreground[0]<viewport.width);if(p>4){assert.ok(s.scene.screenLandmarks.second[0]>0&&s.scene.screenLandmarks.second[0]<viewport.width);const [replay,meter]=await Promise.all([phone.locator('.replay').boundingBox(),phone.locator('.scroll-meter').boundingBox()]);assert.ok(replay.y+replay.height<meter.y||replay.x+replay.width<meter.x||replay.x>meter.x+meter.width,'El indicador no tapa el enlace de regreso');}await capture(phone,`MOVIL-${viewport.width}-${p}`)}await phone.keyboard.press('End');await phone.waitForFunction(()=>window.__puntoes.getState().progress>4.99);await phone.close()}record('A 320, 390 y 768 px no hay desbordamiento y ambos índices permanecen en cuadro');
 const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await ready(reduced);await jump(reduced,4.75);const still=await state(reduced);await reduced.mouse.move(20,20);await reduced.waitForTimeout(1200);assert.deepEqual((await state(reduced)).scene.camera,still.scene.camera);assert.deepEqual((await state(reduced)).scene.fingerCurls,still.scene.fingerCurls);await reduced.close();record('Movimiento reducido: poses estables, sin vaivén ni perspectiva del ratón');
 const fallback=await browser.newPage({viewport:{width:390,height:844}});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /^webgl/.test(type)?null:original.call(this,type,...args)}});await fallback.goto(base);await fallback.waitForFunction(()=>document.body.dataset.render==='fallback');await fallback.getByRole('link',{name:'El encuentro',exact:false}).click();await fallback.waitForTimeout(1400);assert.ok(await fallback.getByText('Las manos se acercan y mantienen una pequeña distancia.',{exact:false}).isVisible());await fallback.close();record('Sin WebGL se conserva una descripción legible del recorrido');
 const noJS=await browser.newPage({viewport:{width:390,height:844},javaScriptEnabled:false});await noJS.goto(base);assert.ok(await noJS.getByRole('heading',{name:'Todo empieza en tus manos.',exact:true}).isVisible());assert.ok(await noJS.getByText('Las manos se acercan y mantienen una pequeña distancia.',{exact:false}).isVisible());await noJS.close();record('Sin JavaScript se pueden leer las descripciones y navegar');
 assert.deepEqual(report.errors,[]);record('Sin errores JavaScript ni errores de compilación de shaders');
}catch(error){report.failure=error.stack;console.error(error);process.exitCode=1}finally{await writeFile(path.join(output,'VALIDACION.json'),JSON.stringify(report,null,2));await browser.close()}
