import{chromium}from'@playwright/test';import assert from'node:assert/strict';import{mkdir,writeFile,readFile}from'node:fs/promises';
const base=process.env.PUNTOES_URL||'http://127.0.0.1:4180/',out=process.env.PUNTOES_QA_OUT||'docs/coordinacion-mano-2026-10-01/TRAMO-820-C1';await mkdir(out,{recursive:true});const baseline=JSON.parse(await readFile('docs/coordinacion-mano-2026-10-01/TRAMO-750-C2/VALIDACION.json','utf8')),oldDistance=baseline.clearance.find(x=>x.marker===820).approximateCentimetres;
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={url:base,date:new Date().toISOString(),errors:[],frames:[],clearance:[],pointer:[],regressions:[],checks:[]};
const state=p=>p.evaluate(()=>window.__puntoes.getState()),delta=(a,b)=>Math.max(...a.map((v,i)=>Math.abs(v-b[i])));
async function ready(p){p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>document.body.dataset.render==='webgl',null,{timeout:60000});await p.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#scene canvas')).opacity)>.99)}
async function jump(p,m){await p.evaluate(m=>scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*m/1000,behavior:'instant'}),m);await p.waitForFunction(m=>Math.abs(window.__puntoes.getState().visualProgress-m/200)<.002,m);await p.waitForFunction(()=>Math.abs(window.__puntoes.getState().visualProgress-window.__puntoes.getState().progress)<.00001)}
async function grab(p,m,label){const s=await state(p),framing=await p.evaluate(()=>window.__puntoes.measureWrenchFraming());await p.screenshot({path:`${out}/${label}.png`});return{viewport:p.viewportSize(),marker:m,state:s,framing}}
function inView(s,v){for(const[role,xy]of Object.entries(s.scene.screenFingerTips))assert.ok(xy[0]>2&&xy[0]<v.width-2&&xy[1]>75&&xy[1]<v.height-2,`${v.width} ${s.scene.normalisedScroll*1000} ${role} ${xy}`)}
try{
 const p=await browser.newPage({viewport:{width:1424,height:873}});await ready(p);await p.mouse.move(712,436.5);await p.waitForTimeout(1500);
 for(const m of [750,780,800,820,835,850,880,900,1000]){await jump(p,m);const row=await grab(p,m,`1424-${m}`);inView(row.state,row.viewport);report.frames.push(row)}
 const peak=report.frames.find(x=>x.marker===820);assert.equal(peak.framing.scale[0],4.2);assert.ok(peak.framing.silhouetteVisibleFraction>.65&&peak.framing.silhouetteVisibleFraction<.8);assert.ok(peak.framing.screenClearance.index.distancePixels>8&&!peak.framing.screenClearance.index.insideToolSilhouette);assert.deepEqual(peak.state.scene.humanScale,[1,-1,1]);
 report.checks.push('820: real depth/palm turn, complete fingers, visible air and ~70% real GLB silhouette at fixed wrench scale4.2');
 for(const m of [750,760,770,780,790,800,810,815,820,825,830,835,840,850,860,870,880]){await jump(p,m);const clearance=await p.evaluate(()=>window.__puntoes.measureClearances().llave);assert.equal(clearance.intersectingTriangles,0);assert.ok(clearance.approximateCentimetres>.5);report.clearance.push({marker:m,...clearance})}
 const distance=report.clearance.find(x=>x.marker===820).approximateCentimetres;assert.ok(distance<oldDistance*.25&&distance>2&&distance<7);report.distanceComparison={previousCentimetres:oldDistance,currentCentimetres:distance,reduction:1-distance/oldDistance};report.checks.push('17 samples750–880: no surface intersection;820 gap reduced by more than75%');
 for(const m of [820,835]){await jump(p,m);for(const[name,x,y]of [['SI',20,20],['SD',1404,20],['II',20,853],['ID',1404,853]]){await p.mouse.move(x,y);await p.waitForTimeout(1600);const row=await grab(p,m,`1424-${m}-${name}`);inView(row.state,row.viewport);for(const role of ['index','thumb'])assert.ok(!row.framing.screenClearance[role].insideToolSilhouette&&row.framing.screenClearance[role].distancePixels>4,`${m} ${name} ${role} visual gap`);const clearance=await p.evaluate(()=>window.__puntoes.measureClearances().llave);assert.equal(clearance.intersectingTriangles,0);report.pointer.push({...row,pointer:name,clearance})}}
 report.checks.push('Parallax corners820/835: thumb/index visible, complete hand and no collision');await p.mouse.move(712,436.5);await p.waitForTimeout(2000);
 for(const m of [385,500,750,900,1000]){await jump(p,m);const s=await state(p),original=m===385||m===500?null:baseline.frames.find(x=>x.marker===m&&!x.pointer).state.scene;if(original){assert.ok(delta(s.scene.humanPosition,original.humanPosition)<.01);assert.ok(delta(s.scene.humanRotation,original.humanRotation)<.001);for(const name of Object.keys(original.indexJoints))assert.ok(delta(s.scene.indexJoints[name],original.indexJoints[name])<.002);if(m===1000)assert.ok(Math.abs(s.scene.contactGap-original.contactGap)<.00001)}else if(m===385)assert.equal(s.scene.tools.find(t=>t.id==='piedra').visible,false);else{const c=await p.evaluate(()=>window.__puntoes.measureClearances().compas);assert.equal(c.intersectingTriangles,0);assert.ok(c.approximateCentimetres>3&&c.approximateCentimetres<4)}report.regressions.push({marker:m,state:s})}
 await jump(p,820);const first=(await state(p)).scene;for(const m of [835,880,1000,900,850,820])await jump(p,m);const returned=(await state(p)).scene;assert.ok(delta(first.humanPosition,returned.humanPosition)<.005);const before=(await state(p)).scene.tools.find(x=>x.id==='llave');await p.waitForTimeout(1000);assert.deepEqual((await state(p)).scene.tools.find(x=>x.id==='llave'),before);report.checks.push('385/500/750/900/1000 preserved; reversible reach and no time-based wrench motion');await p.close();
 for(const viewport of [{width:320,height:640},{width:390,height:844},{width:768,height:1024}]){const p=await browser.newPage({viewport});await ready(p);for(const m of [750,780,800,820,835,850,880,900,1000]){await jump(p,m);const row=await grab(p,m,`${viewport.width}-${m}`);inView(row.state,viewport);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(m===820||m===835){for(const role of ['index','thumb'])assert.ok(!row.framing.screenClearance[role].insideToolSilhouette&&row.framing.screenClearance[role].distancePixels>5,`${viewport.width} ${m} ${role} air`);const c=await p.evaluate(()=>window.__puntoes.measureClearances().llave);assert.equal(c.intersectingTriangles,0);row.clearance=c;}report.frames.push(row)}await p.close()}
 report.checks.push('320/390/768: complete hand, thumb/index clear of actual wrench silhouette, physically separate near reach, preserved ending');assert.deepEqual(report.errors,[]);report.passed=true;console.log('✓ Reach820 geometry, parallax, responsive, contact and regression checks');
}catch(e){report.failure=e.stack;console.error(e);process.exitCode=1}finally{await writeFile(`${out}/VALIDACION-GEOMETRIA.json`,JSON.stringify(report,null,2));await browser.close()}
